---
# yamllint disable rule:line-length
name: Build, publish and test Ubuntu images

on:  # yamllint disable-line rule:truthy
  workflow_call:
    secrets:
      OS_CLOUDS:
        description: clouds.yaml file
        required: true
      S3_ACCESS_KEY:
        description: S3 access key
        required: true
      S3_SECRET_KEY:
        description: S3 secret key
        required: true

jobs:
  read_builds:
    runs-on: ubuntu-latest
    outputs:
      builds: ${{ steps.builds-as-json.outputs.builds }}
    permissions:
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install script dependencies
        run: pip install -r ./requirements.txt

      - name: Get builds as JSON
        id: builds-as-json
        run: ./bin/builds-as-json

  ensure_source_image:
    needs:
      - read_builds
    runs-on: ubuntu-latest
    outputs:
      source_image: ${{ steps.download_source.outputs.source_image_name }}
    permissions:
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install script dependencies
        run: pip install -r ./requirements.txt

      - name: Write OpenStack credentials
        run: echo "$OS_CLOUDS" > ./clouds.yaml
        env:
          OS_CLOUDS: ${{ secrets.OS_CLOUDS }}

      - name: Download source image and upload to OpenStack
        id: download_source
        run: ./bin/ensure-source-image
        env:
          BUILD_MATRIX: ${{ needs.read_builds.outputs.builds }}
          REPO_ROOT: ${{ github.workspace }}
          GH_ACTIONS_RUN: "true"
          OS_CLOUD: ${{ vars.TARGET_CLOUD }}

  build_images:
    needs:
      - read_builds
      - ensure_source_image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.read_builds.outputs.builds) }}
    name: ${{ matrix.name }}
    permissions:
      actions: read
      contents: write
      packages: write
      id-token: write  # required to get an OIDC token for signing
      security-events: write  # required to upload SARIF files
      checks: write # to write check-runs statuses
    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      - name: Write OpenStack credentials
        run: echo "$OS_CLOUDS" > ./clouds.yaml
        env:
          OS_CLOUDS: ${{ secrets.OS_CLOUDS }}

      - name: Set up Packer environment
        run: ./bin/setup
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        id: build-image
        run: ./bin/build-image
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Build the image on the target cloud
          OS_CLOUD: ${{ vars.TARGET_CLOUD }}
          ENVIRONMENT: ${{ vars.TARGET_CLOUD }}
          PACKER_TEMPLATE: ${{ matrix.template }}
          ENV_VAR_FILES: ${{ matrix.var-files }}
          PKR_VAR_source_image_name: ${{ needs.ensure_source_image.outputs.source_image }}
          SKIP_SOURCE_IMAGE: "false"
